services:
  - type: web
    name: wellnesscheck-backend
    runtime: docker
    plan: free
    rootDir: WellnessCheck.API
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=localhost;Port=5432;Database=WellnessCheckDb;Username=postgres;Password=CCnick24
      - key: Jwt__Key
        value: welnesscheck-api-nicolas242424@@@@@@
