services:
  - type: web
    name: wellnesscheck-backend
    runtime: docker
    plan: free
    rootDir: WellnessCheck.API
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: postgresql://wellnesscheck-db_owner:npg_nh8DWg5tIApx@ep-quiet-frog-a5meqvsk-pooler.us-east-2.aws.neon.tech/wellnesscheck-db?sslmode=require
      - key: Jwt__Key
        value: welnesscheck-api-nicolas242424@@@@@@
